version: '3.8'

services:
  ejercicio4-app:
    build: .
    container_name: ejercicio4_app
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:15-alpine
    container_name: ejercicio4_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: ejercicio4_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ejercicio4_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
